In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Big_Cities_Health_Data_Inventory.csv')

In [3]:
df.head()

,Indicator Category,Indicator,Year,Gender,Race/ Ethnicity,Value,Place,BCHC Requested Methodology,Source,Methods,Notes
0,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2013,Both,All,30.4,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
1,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2012,Both,All,39.6,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
2,HIV/AIDS,"AIDS Diagnoses Rate (Per 100,000 people)",2011,Both,All,41.7,"Atlanta (Fulton County), GA","AIDS cases diagnosed in 2012, 2013, 2014 (as a...",Diagnoses numbers were obtained from the Georg...,NaN,NaN
3,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Male,All,195.8,"Atlanta (Fulton County), GA","2012, 2013, 2014; per 100,000 population using...","National Center for Health Statistics (NCHS), CDC",NaN,NaN
4,Cancer,All Types of Cancer Mortality Rate (Age-Adjust...,2013,Female,All,135.5,"Atlanta (Fulton County), GA","2012, 2013, 2014; per 100,000 population using...","National Center for Health Statistics (NCHS), CDC",NaN,NaN

In [4]:
df.head(10).T

,0,1,2,3,4,5,6,7,8,9
Indicator Category,HIV/AIDS,HIV/AIDS,HIV/AIDS,Cancer,Cancer,Cancer,Cancer,Cancer,Cancer,Cancer
Indicator,"AIDS Diagnoses Rate (Per 100,000 people)","AIDS Diagnoses Rate (Per 100,000 people)","AIDS Diagnoses Rate (Per 100,000 people)",All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...,All Types of Cancer Mortality Rate (Age-Adjust...
Year,2013,2012,2011,2013,2013,2013,2012,2012,2012,2011
Gender,Both,Both,Both,Male,Female,Both,Male,Female,Both,Male
Race/ Ethnicity,All,All,All,All,All,All,All,All,All,All
Value,30.4,39.6,41.7,195.8,135.5,159.3,199.2,137.6,160.3,196.2
Place,"Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA","Atlanta (Fulton County), GA"
BCHC Requested Methodology,"AIDS cases diagnosed in 2012, 2013, 2014 (as a...","AIDS cases diagnosed in 2012, 2013, 2014 (as a...","AIDS cases diagnosed in 2012, 2013, 2014 (as a...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using...","2012, 2013, 2014; per 100,000 population using..."
Source,Diagnoses numbers were obtained from the Georg...,Diagnoses numbers were obtained from the Georg...,Diagnoses numbers were obtained from the Georg...,"National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC","National Center for Health Statistics (NCHS), CDC"
Methods,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Notes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df['Indicator Category'].value_counts()

HIV/AIDS                                    2177
Injury and Violence                         1916
Nutrition, Physical Activity, & Obesity     1841
Infectious Disease                          1486
Cancer                                      1432
Maternal and Child Health                   1323
Behavioral Health/Substance Abuse            983
Food Safety                                  874
Life Expectancy and Death Rate (Overall)     544
Demographics                                 504
Tobacco                                      432
Name: Indicator Category, dtype: int64

In [6]:
df_clean = df[['Indicator Category','Indicator','Place','Value']]

In [7]:
df_health = df_clean[df_clean['Indicator Category'] =='Life Expectancy and Death Rate (Overall)']

In [8]:
df_health['Indicator'].value_counts()

All-Cause Mortality Rate (Age-Adjusted; Per 100,000 people)    389
Life Expectancy at Birth (Years)                               155
Name: Indicator, dtype: int64

In [9]:
df_expectancy= df_health[df_health['Indicator']=='Life Expectancy at Birth (Years)']

In [10]:
df_expectancy['Place'].value_counts()

Portland (Multnomah County), OR    24
San Diego County, CA               21
Long Beach, CA                     13
U.S. Total                         12
San Francisco, CA                   7
Boston, MA                          7
Cleveland, OH                       7
Las Vegas (Clark County), NV        7
Los Angeles, CA                     7
Seattle, WA                         6
Oakland, CA                         6
San Antonio, TX                     6
Washington, DC                      6
New York, NY                        6
Fort Worth (Tarrant County), TX     5
Kansas City, MO                     5
Denver, CO                          3
Philadelphia, PA                    2
Atlanta (Fulton County), GA         1
Miami (Miami-Dade County), FL       1
Chicago, IL                         1
Baltimore, MD                       1
Phoenix, AZ                         1
Name: Place, dtype: int64

In [11]:
new = df_expectancy['Place'].str.split(',',n=1,expand=True)

In [12]:
df_expectancy['city']=new[0]

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [13]:
df_expectancy['state']=new[1]

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
df_expectancy.drop(columns=['Place'],inplace = True)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [15]:
df_expectancy.head()

,Indicator Category,Indicator,Value,city,state
50,Life Expectancy and Death Rate (Overall),Life Expectancy at Birth (Years),78.0,Atlanta (Fulton County),GA
120,Life Expectancy and Death Rate (Overall),Life Expectancy at Birth (Years),70.4,Cleveland,OH
159,Life Expectancy and Death Rate (Overall),Life Expectancy at Birth (Years),76.7,Cleveland,OH
366,Life Expectancy and Death Rate (Overall),Life Expectancy at Birth (Years),73.9,Baltimore,MD
427,Life Expectancy and Death Rate (Overall),Life Expectancy at Birth (Years),73.6,Cleveland,OH

In [16]:
df_expectancy['city'].value_counts()

Portland (Multnomah County)    24
San Diego County               21
Long Beach                     13
U.S. Total                     12
San Francisco                   7
Cleveland                       7
Las Vegas (Clark County)        7
Boston                          7
Los Angeles                     7
Oakland                         6
San Antonio                     6
New York                        6
Seattle                         6
Washington                      6
Kansas City                     5
Fort Worth (Tarrant County)     5
Denver                          3
Philadelphia                    2
Baltimore                       1
Phoenix                         1
Atlanta (Fulton County)         1
Chicago                         1
Miami (Miami-Dade County)       1
Name: city, dtype: int64

In [17]:
df_expectancy = df_expectancy.replace({'Portland (Multnomah County)':'Portland','San Diego County':'San Diego','Las Vegas (Clark County)':'Las Vegas','Fort Worth (Tarrant County)':'Fort Worth','Miami (Miami-Dade County)':'Miami','Atlanta (Fulton County)':'Atlanta'})

In [18]:
df_expectancy = df_expectancy[['Value','city','state']]

In [19]:
df_expectancy = df_expectancy.rename(columns={'Value':'life_expectancy'})

In [20]:
df_expectancy = df_expectancy.reset_index(drop=True)

In [21]:
df_expectancy.head()

   life_expectancy       city state
0             78.0    Atlanta    GA
1             70.4  Cleveland    OH
2             76.7  Cleveland    OH
3             73.9  Baltimore    MD
4             73.6  Cleveland    OH

In [22]:
df_expectancy.to_csv('expectancy.csv')